flowchart TD
    A[App Revolut|smartphone|#BCE8F8|Pagador|60|60]
    B[SDK PSP Niubiz|shield|#C0E6F0|SDK|60|200]
    T[PSP Niubiz|server|#BCE8F8|PSP|60|340]
    C[UPI Switch|building|#D0D8F8|Red|320|300]
    E[Banco Revolut|building|#D7F6D4|Emisor|60|500]
    F[Banco Yape|building|#D7F6D4|Receptor|580|500]
    G[App Yape|smartphone|#F8E8BC|Beneficiario|580|60]
    H[PSP Yape|creditcard|#F8E8BC|PSP|580|200]

    A -->|1 Inicia UPI|3000| B
    B -->|2 SDK upi PIN|3000| T
    T -->|3 Petición a NPCI|3500| C
    C -->|4 A Banco Emisor|3000| E
    E -->|5 Debita y Confirma|2500| C
    C -->|6 A Banco Receptor|3000| F
    F -->|7 Abona y Confirma|2500| C
    C -->|8 Notifica a PSP Pagador|3000| T
    T -->|9 Notifica a SDK|2500| B
    B -->|10 Notifica a App Pagador|2500| A
    C -->|11 Notifica a PSP Beneficiario|3000| H
    H -->|12 Notifica a App Beneficiario|2500| G